name: Génération RSS pour Lidarr

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install rss
      - run: node generate-rss.js
      - name: Commit et push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/artists.xml docs/.nojekyll
          git commit -m "Mise à jour du flux RSS"
          git push
