name: Génération RSS pour Lidarr

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install rss
      - run: node generate-rss.js
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com"
      - run: |
          git add docs/artists.xml
          git commit -m "Mise à jour du flux RSS"
          git push
